In [1]:
import pandas as pd
from pymcprophet.model import BayesTS, BayesTSConfig
from prophet import Prophet

Importing plotly failed. Interactive plots will not work.

In [2]:
df = df = pd.read_csv('https://raw.githubusercontent.com/facebook/prophet/main/examples/example_wp_log_peyton_manning.csv')
df['ds'] = pd.to_datetime(df['ds'])

In [3]:
len(set(df["y"].unique()))

2357

## Model Matrix

In [4]:
# ts_config = BayesTSConfig(daily_seasonality="disabled", weekly_seasonality="disabled", yearly_seasonality="disabled")
ts_config = BayesTSConfig()
ts_model = BayesTS(ts_config)
ts_model.assign_model_matrix(df)

ts_model.model_df

,ds,y,y_trans,t_seasonality,yearly_sin_1,yearly_sin_2,yearly_sin_3,yearly_sin_4,yearly_sin_5,yearly_sin_6,...,yearly_cos_7,yearly_cos_8,yearly_cos_9,yearly_cos_10,weekly_sin_1,weekly_sin_2,weekly_sin_3,weekly_cos_1,weekly_cos_2,weekly_cos_3
0,2007-12-10,9.590761,0.746552,13857.0,-0.377462,-0.699079,-0.917267,-0.999745,-0.934311,-0.730644,...,-0.908042,-0.998981,-0.942120,-0.745872,-4.338837e-01,7.818315e-01,-9.749279e-01,-0.900969,0.623490,-0.222521
1,2007-12-11,8.519590,0.663171,13858.0,-0.361478,-0.674069,-0.895501,-0.995827,-0.961479,-0.797102,...,-0.851148,-0.983343,-0.982552,-0.848883,-9.749279e-01,4.338837e-01,7.818315e-01,-0.222521,-0.900969,0.623490
2,2007-12-12,8.183677,0.637023,13859.0,-0.345386,-0.648262,-0.871351,-0.987196,-0.981538,-0.855075,...,-0.781927,-0.949111,-0.999480,-0.926834,-7.818315e-01,-9.749279e-01,-4.338837e-01,0.623490,-0.222521,-0.900969
3,2007-12-13,8.072467,0.628367,13860.0,-0.329192,-0.621687,-0.844881,-0.973892,-0.994341,-0.903946,...,-0.701382,-0.896932,-0.992498,-0.977426,5.505235e-14,1.101047e-13,1.984146e-12,1.000000,1.000000,1.000000
4,2007-12-14,7.893572,0.614441,13861.0,-0.312900,-0.594376,-0.816160,-0.955979,-0.999791,-0.943196,...,-0.610679,-0.827793,-0.961774,-0.999166,7.818315e-01,9.749279e-01,4.338837e-01,0.623490,-0.222521,-0.900969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2900,2016-01-16,7.817223,0.608498,16816.0,0.246857,0.478434,0.680398,0.840248,0.948090,0.997250,...,-0.174354,-0.412034,-0.624210,-0.797750,9.749279e-01,-4.338837e-01,-7.818315e-01,-0.222521,-0.900969,0.623490
2901,2016-01-17,9.273878,0.721885,16817.0,0.263489,0.508356,0.717295,0.875539,0.971904,0.999579,...,-0.291378,-0.533137,-0.737217,-0.889193,4.338837e-01,-7.818315e-01,9.749279e-01,-0.900969,0.623490,-0.222521
2902,2016-01-18,10.333775,0.804388,16818.0,0.280044,0.537677,0.752283,0.906686,0.988531,0.991269,...,-0.404181,-0.644159,-0.832588,-0.954388,-4.338837e-01,7.818315e-01,-9.749279e-01,-0.900969,0.623490,-0.222521
2903,2016-01-19,9.125871,0.710364,16819.0,0.296516,0.566362,0.785267,0.933542,0.997850,0.972408,...,-0.511131,-0.743001,-0.908042,-0.991410,-9.749279e-01,4.338837e-01,7.818315e-01,-0.222521,-0.900969,0.623490
2904,2016-01-20,8.891374,0.692111,16820.0,0.312900,0.594376,0.816160,0.955979,0.999791,0.943196,...,-0.610679,-0.827793,-0.961774,-0.999166,-7.818315e-01,-9.749279e-01,-4.338837e-01,0.623490,-0.222521,-0.900969

In [5]:
ts_model.model_df

,ds,y,y_trans,t_seasonality,yearly_sin_1,yearly_sin_2,yearly_sin_3,yearly_sin_4,yearly_sin_5,yearly_sin_6,...,yearly_cos_7,yearly_cos_8,yearly_cos_9,yearly_cos_10,weekly_sin_1,weekly_sin_2,weekly_sin_3,weekly_cos_1,weekly_cos_2,weekly_cos_3
0,2007-12-10,9.590761,0.746552,13857.0,-0.377462,-0.699079,-0.917267,-0.999745,-0.934311,-0.730644,...,-0.908042,-0.998981,-0.942120,-0.745872,-4.338837e-01,7.818315e-01,-9.749279e-01,-0.900969,0.623490,-0.222521
1,2007-12-11,8.519590,0.663171,13858.0,-0.361478,-0.674069,-0.895501,-0.995827,-0.961479,-0.797102,...,-0.851148,-0.983343,-0.982552,-0.848883,-9.749279e-01,4.338837e-01,7.818315e-01,-0.222521,-0.900969,0.623490
2,2007-12-12,8.183677,0.637023,13859.0,-0.345386,-0.648262,-0.871351,-0.987196,-0.981538,-0.855075,...,-0.781927,-0.949111,-0.999480,-0.926834,-7.818315e-01,-9.749279e-01,-4.338837e-01,0.623490,-0.222521,-0.900969
3,2007-12-13,8.072467,0.628367,13860.0,-0.329192,-0.621687,-0.844881,-0.973892,-0.994341,-0.903946,...,-0.701382,-0.896932,-0.992498,-0.977426,5.505235e-14,1.101047e-13,1.984146e-12,1.000000,1.000000,1.000000
4,2007-12-14,7.893572,0.614441,13861.0,-0.312900,-0.594376,-0.816160,-0.955979,-0.999791,-0.943196,...,-0.610679,-0.827793,-0.961774,-0.999166,7.818315e-01,9.749279e-01,4.338837e-01,0.623490,-0.222521,-0.900969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2900,2016-01-16,7.817223,0.608498,16816.0,0.246857,0.478434,0.680398,0.840248,0.948090,0.997250,...,-0.174354,-0.412034,-0.624210,-0.797750,9.749279e-01,-4.338837e-01,-7.818315e-01,-0.222521,-0.900969,0.623490
2901,2016-01-17,9.273878,0.721885,16817.0,0.263489,0.508356,0.717295,0.875539,0.971904,0.999579,...,-0.291378,-0.533137,-0.737217,-0.889193,4.338837e-01,-7.818315e-01,9.749279e-01,-0.900969,0.623490,-0.222521
2902,2016-01-18,10.333775,0.804388,16818.0,0.280044,0.537677,0.752283,0.906686,0.988531,0.991269,...,-0.404181,-0.644159,-0.832588,-0.954388,-4.338837e-01,7.818315e-01,-9.749279e-01,-0.900969,0.623490,-0.222521
2903,2016-01-19,9.125871,0.710364,16819.0,0.296516,0.566362,0.785267,0.933542,0.997850,0.972408,...,-0.511131,-0.743001,-0.908042,-0.991410,-9.749279e-01,4.338837e-01,7.818315e-01,-0.222521,-0.900969,0.623490
2904,2016-01-20,8.891374,0.692111,16820.0,0.312900,0.594376,0.816160,0.955979,0.999791,0.943196,...,-0.610679,-0.827793,-0.961774,-0.999166,-7.818315e-01,-9.749279e-01,-4.338837e-01,0.623490,-0.222521,-0.900969

## Logistic

In [6]:
df_logistic = df.copy()
df_logistic["cap"] = 10

ts_config = BayesTSConfig(growth="logistic", seasonality_mode="multiplicative")
ts_model = BayesTS(ts_config)
ts_model.assign_model_matrix(df_logistic)

ts_model.model_df

,ds,y,cap,y_trans,t_seasonality,yearly_sin_1,yearly_sin_2,yearly_sin_3,yearly_sin_4,yearly_sin_5,...,yearly_cos_7,yearly_cos_8,yearly_cos_9,yearly_cos_10,weekly_sin_1,weekly_sin_2,weekly_sin_3,weekly_cos_1,weekly_cos_2,weekly_cos_3
0,2007-12-10,9.590761,10,0.746552,13857.0,-0.377462,-0.699079,-0.917267,-0.999745,-0.934311,...,-0.908042,-0.998981,-0.942120,-0.745872,-4.338837e-01,7.818315e-01,-9.749279e-01,-0.900969,0.623490,-0.222521
1,2007-12-11,8.519590,10,0.663171,13858.0,-0.361478,-0.674069,-0.895501,-0.995827,-0.961479,...,-0.851148,-0.983343,-0.982552,-0.848883,-9.749279e-01,4.338837e-01,7.818315e-01,-0.222521,-0.900969,0.623490
2,2007-12-12,8.183677,10,0.637023,13859.0,-0.345386,-0.648262,-0.871351,-0.987196,-0.981538,...,-0.781927,-0.949111,-0.999480,-0.926834,-7.818315e-01,-9.749279e-01,-4.338837e-01,0.623490,-0.222521,-0.900969
3,2007-12-13,8.072467,10,0.628367,13860.0,-0.329192,-0.621687,-0.844881,-0.973892,-0.994341,...,-0.701382,-0.896932,-0.992498,-0.977426,5.505235e-14,1.101047e-13,1.984146e-12,1.000000,1.000000,1.000000
4,2007-12-14,7.893572,10,0.614441,13861.0,-0.312900,-0.594376,-0.816160,-0.955979,-0.999791,...,-0.610679,-0.827793,-0.961774,-0.999166,7.818315e-01,9.749279e-01,4.338837e-01,0.623490,-0.222521,-0.900969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2900,2016-01-16,7.817223,10,0.608498,16816.0,0.246857,0.478434,0.680398,0.840248,0.948090,...,-0.174354,-0.412034,-0.624210,-0.797750,9.749279e-01,-4.338837e-01,-7.818315e-01,-0.222521,-0.900969,0.623490
2901,2016-01-17,9.273878,10,0.721885,16817.0,0.263489,0.508356,0.717295,0.875539,0.971904,...,-0.291378,-0.533137,-0.737217,-0.889193,4.338837e-01,-7.818315e-01,9.749279e-01,-0.900969,0.623490,-0.222521
2902,2016-01-18,10.333775,10,0.804388,16818.0,0.280044,0.537677,0.752283,0.906686,0.988531,...,-0.404181,-0.644159,-0.832588,-0.954388,-4.338837e-01,7.818315e-01,-9.749279e-01,-0.900969,0.623490,-0.222521
2903,2016-01-19,9.125871,10,0.710364,16819.0,0.296516,0.566362,0.785267,0.933542,0.997850,...,-0.511131,-0.743001,-0.908042,-0.991410,-9.749279e-01,4.338837e-01,7.818315e-01,-0.222521,-0.900969,0.623490
2904,2016-01-20,8.891374,10,0.692111,16820.0,0.312900,0.594376,0.816160,0.955979,0.999791,...,-0.610679,-0.827793,-0.961774,-0.999166,-7.818315e-01,-9.749279e-01,-4.338837e-01,0.623490,-0.222521,-0.900969

## Holidays

In [7]:
playoffs = pd.DataFrame({
  'holiday': 'playoff',
  'ds': pd.to_datetime(['2008-01-13', '2009-01-03', '2010-01-16',
                        '2010-01-24', '2010-02-07', '2011-01-08',
                        '2013-01-12', '2014-01-12', '2014-01-19',
                        '2014-02-02', '2015-01-11', '2016-01-17',
                        '2016-01-24', '2016-02-07']),
  'lower_window': 0,
  'upper_window': 1,
})
superbowls = pd.DataFrame({
  'holiday': 'superbowl',
  'ds': pd.to_datetime(['2010-02-07', '2014-02-02', '2016-02-07']),
  'lower_window': 0,
  'upper_window': 1,
})
holidays = pd.concat((playoffs, superbowls))
holidays

      holiday         ds  lower_window  upper_window
0     playoff 2008-01-13             0             1
1     playoff 2009-01-03             0             1
2     playoff 2010-01-16             0             1
3     playoff 2010-01-24             0             1
4     playoff 2010-02-07             0             1
5     playoff 2011-01-08             0             1
6     playoff 2013-01-12             0             1
7     playoff 2014-01-12             0             1
8     playoff 2014-01-19             0             1
9     playoff 2014-02-02             0             1
10    playoff 2015-01-11             0             1
11    playoff 2016-01-17             0             1
12    playoff 2016-01-24             0             1
13    playoff 2016-02-07             0             1
0   superbowl 2010-02-07             0             1
1   superbowl 2014-02-02             0             1
2   superbowl 2016-02-07             0             1

In [8]:
train_df = df.query("ds.dt.year < 2014")
test_df = df.query("ds.dt.year > 2014")



ts_config = BayesTSConfig()
ts_model = BayesTS(ts_config)
ts_model.add_holiday_country("US")
ts_model.add_holiday(holidays)
ts_model.assign_model_matrix(train_df)

ts_model.model_df

,ds,y,y_trans,t_seasonality,yearly_sin_1,yearly_sin_2,yearly_sin_3,yearly_sin_4,yearly_sin_5,yearly_sin_6,...,NewYearsDayobserved,JuneteenthNationalIndependenceDayobserved,ChristmasDayobserved,VeteransDayobserved,weekly_sin_1,weekly_sin_2,weekly_sin_3,weekly_cos_1,weekly_cos_2,weekly_cos_3
0,2007-12-10,9.590761,0.756755,13857.0,-0.377462,-0.699079,-0.917267,-0.999745,-0.934311,-0.730644,...,0,0,0,0,-4.338837e-01,7.818315e-01,-9.749279e-01,-0.900969,0.623490,-0.222521
1,2007-12-11,8.519590,0.672234,13858.0,-0.361478,-0.674069,-0.895501,-0.995827,-0.961479,-0.797102,...,0,0,0,0,-9.749279e-01,4.338837e-01,7.818315e-01,-0.222521,-0.900969,0.623490
2,2007-12-12,8.183677,0.645729,13859.0,-0.345386,-0.648262,-0.871351,-0.987196,-0.981538,-0.855075,...,0,0,0,0,-7.818315e-01,-9.749279e-01,-4.338837e-01,0.623490,-0.222521,-0.900969
3,2007-12-13,8.072467,0.636954,13860.0,-0.329192,-0.621687,-0.844881,-0.973892,-0.994341,-0.903946,...,0,0,0,0,5.505235e-14,1.101047e-13,1.984146e-12,1.000000,1.000000,1.000000
4,2007-12-14,7.893572,0.622839,13861.0,-0.312900,-0.594376,-0.816160,-0.955979,-0.999791,-0.943196,...,0,0,0,0,7.818315e-01,9.749279e-01,4.338837e-01,0.623490,-0.222521,-0.900969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2154,2013-12-27,8.488999,0.669821,16066.0,-0.085906,-0.171177,-0.255182,-0.337301,-0.416926,-0.493468,...,0,0,0,0,7.818315e-01,9.749279e-01,4.338837e-01,0.623490,-0.222521,-0.900969
2155,2013-12-28,8.505728,0.671141,16067.0,-0.068755,-0.137185,-0.204966,-0.271777,-0.337301,-0.401229,...,0,0,0,0,9.749279e-01,-4.338837e-01,-7.818315e-01,-0.222521,-0.900969,0.623490
2156,2013-12-29,9.300090,0.733819,16068.0,-0.051584,-0.103031,-0.154204,-0.204966,-0.255182,-0.304719,...,0,0,0,0,4.338837e-01,-7.818315e-01,9.749279e-01,-0.900969,0.623490,-0.222521
2157,2013-12-30,10.146159,0.800578,16069.0,-0.034398,-0.068755,-0.103031,-0.137185,-0.171177,-0.204966,...,0,0,0,0,-4.338837e-01,7.818315e-01,-9.749279e-01,-0.900969,0.623490,-0.222521
2158,2013-12-31,9.177094,0.724114,16070.0,-0.017202,-0.034398,-0.051584,-0.068755,-0.085906,-0.103031,...,0,0,0,0,-9.749279e-01,4.338837e-01,7.818315e-01,-0.222521,-0.900969,0.623490

In [9]:
ts_model.produce_model_matrix(test_df)

,ds,y,y_trans,t_seasonality,yearly_sin_1,yearly_sin_2,yearly_sin_3,yearly_sin_4,yearly_sin_5,yearly_sin_6,...,NewYearsDayobserved,JuneteenthNationalIndependenceDayobserved,ChristmasDayobserved,VeteransDayobserved,weekly_sin_1,weekly_sin_2,weekly_sin_3,weekly_cos_1,weekly_cos_2,weekly_cos_3
2522,2015-01-01,7.846590,0.619132,16436.0,-0.004301,-0.008601,-0.012901,-0.017202,-0.021501,-0.025801,...,0,0,0,0,-6.035158e-13,-1.207032e-12,-3.629537e-12,1.000000,1.000000,1.000000
2523,2015-01-02,8.302018,0.655067,16437.0,0.012901,0.025801,0.038696,0.051584,0.064464,0.077334,...,0,0,0,0,7.818315e-01,9.749279e-01,4.338837e-01,0.623490,-0.222521,-0.900969
2524,2015-01-03,8.436200,0.665654,16438.0,0.030100,0.060172,0.090190,0.120126,0.149953,0.179645,...,0,0,0,0,9.749279e-01,-4.338837e-01,-7.818315e-01,-0.222521,-0.900969,0.623490
2525,2015-01-04,8.934587,0.704979,16439.0,0.047289,0.094472,0.141444,0.188099,0.234334,0.280044,...,0,0,0,0,4.338837e-01,-7.818315e-01,9.749279e-01,-0.900969,0.623490,-0.222521
2526,2015-01-05,8.888619,0.701352,16440.0,0.064464,0.128661,0.192322,0.255182,0.316982,0.377462,...,0,0,0,0,-4.338837e-01,7.818315e-01,-9.749279e-01,-0.900969,0.623490,-0.222521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2900,2016-01-16,7.817223,0.616814,16816.0,0.246857,0.478434,0.680398,0.840248,0.948090,0.997250,...,0,0,0,0,9.749279e-01,-4.338837e-01,-7.818315e-01,-0.222521,-0.900969,0.623490
2901,2016-01-17,9.273878,0.731751,16817.0,0.263489,0.508356,0.717295,0.875539,0.971904,0.999579,...,0,0,0,0,4.338837e-01,-7.818315e-01,9.749279e-01,-0.900969,0.623490,-0.222521
2902,2016-01-18,10.333775,0.815382,16818.0,0.280044,0.537677,0.752283,0.906686,0.988531,0.991269,...,0,0,0,0,-4.338837e-01,7.818315e-01,-9.749279e-01,-0.900969,0.623490,-0.222521
2903,2016-01-19,9.125871,0.720073,16819.0,0.296516,0.566362,0.785267,0.933542,0.997850,0.972408,...,0,0,0,0,-9.749279e-01,4.338837e-01,7.818315e-01,-0.222521,-0.900969,0.623490
2904,2016-01-20,8.891374,0.701570,16820.0,0.312900,0.594376,0.816160,0.955979,0.999791,0.943196,...,0,0,0,0,-7.818315e-01,-9.749279e-01,-4.338837e-01,0.623490,-0.222521,-0.900969

## Seasonality

Compare Seasonality To Prophet

In [10]:
ts_config = BayesTSConfig()
ts_model = BayesTS(ts_config)
ts_model.assign_model_matrix(df)

ts_model_seasonality_terms = ts_model.produce_model_matrix(df)[ts_model.model_spec.get_seasonality_feature_cols()]
ts_model_sine_cols = [c for c in ts_model_seasonality_terms.columns if "sin" in c]
ts_model_sine_terms = ts_model_seasonality_terms[ts_model_sine_cols]

propet_model =  Prophet()
transformed = propet_model.preprocess(df)
prophet_seasonality_terms = transformed.X

prophet_sine_cols = [c for c in prophet_seasonality_terms.columns if int(c.split("_")[-1]) % 2]
prophet_sine_terms = prophet_seasonality_terms[prophet_sine_cols]

max_dif = (ts_model_sine_terms.values - ts_model_sine_terms.values).max()

print(max_dif)

0.0